export const LOAD_COLLECTIONS_SUCCESS = 'LOAD_COLLECTIONS_SUCCESS';
export const LOAD_COLLECTION_TYPES_SUCCESS = 'LOAD_COLLECTION_TYPES_SUCCESS';
export const UPDATE_COLLECTION_SUCCESS = 'UPDATE_COLLECTION_SUCCESS';
export const CREATE_COLLECTION_SUCCESS = 'CREATE_COLLECTION_SUCCESS';